### ISSUE TITLE
Invalid exception class used by chdb constructor.

### ISSUE THREAD

**Issue by zyxist** [lcastelli/chdb#2]
Currently, chdb throws "Exception" class object, when it cannot find the memory-mapped file. However, this exception is semantically incorrect in this place which forces us to wrap it in try{ }catch{} just to rewrite it into a different object, if our system relies on the exception types to decide what to do with them.

The valid exception is **RuntimeException**: http://docs.php.net/manual/en/class.runtimeexception.php

The change does not break the backward compatibility.

**Comment by lcastelli** [comment]
Thanks, it looks like RuntimeException is indeed more correct.

I've pushed a patch that changes the exception type in RuntimeException in both the chdb constructor and in case of errors during chdb_create.
